### ISSUE TITLE
User Activities

### ISSUE THREAD

**Issue by mod** [rubykube/barong2#29]
## Users has_many Activities
```
user_id
user_ip
user_agent
category
action
result
data
created_at
```

| *story* | column category | column action | column result |
|--------|--------|--------|--------|
|  login success | session | login | succeed |
|  login fail | session | session:create | failed |
|  2FA | user | otp:enable | succeed |
|  Password reset requested | user | password:reset:request | succeed |
|  Password reseted | user | password:reset:confirmed | succeed |
|  Password changed | user | password:update | succeed |

**Comment by ec** [comment]
#30 base is here

**Comment by ec** [comment]
#30 #31
